# Generated by Django 3.1.3 on 2021-03-17 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('P5', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dishcategory',
            options={'verbose_name': 'Gerichtskategorie', 'verbose_name_plural': 'Gerichtskategorien'},
        ),
        migrations.AlterModelOptions(
            name='dishtyp',
            options={'verbose_name': 'Gerichtsvariate', 'verbose_name_plural': 'Gerichtsvariaten'},
        ),
        migrations.RenameField(
            model_name='order',
            old_name='Table_Nr',
            new_name='table_nr',
        ),
    ]
