# Generated by Django 3.2.1 on 2021-05-04 11:02

from django.db import migrations, models
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('P5', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dishcategory',
            name='sequence',
            field=models.IntegerField(default=3, verbose_name='Reihenfolgen'),
        ),
        migrations.AlterField(
            model_name='dish',
            name='price',
            field=djmoney.models.fields.MoneyField(currency_choices=(('EUR', 'EURO/€'),), decimal_places=2, default_currency='EUR', max_digits=9),
        ),
        migrations.AlterField(
            model_name='dish',
            name='price_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('EUR', 'EURO/€')], default='EUR', editable=False, max_length=3),
        ),
    ]
