# Generated by Django 3.0.5 on 2021-02-20 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('P5', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='Dish_ID',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
