# Generated by Django 3.2.1 on 2021-05-04 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('P5', '0002_auto_20210504_1302'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='confirmation',
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('open', 'öffen'), ('working', 'im Gange'), ('closed', 'abgeschlossen')], default='open', max_length=30),
        ),
    ]
