# Generated by Django 3.0.5 on 2021-02-21 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('P5', '0002_auto_20210221_0032'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('Order_ID', models.AutoField(primary_key=True, serialize=False)),
                ('Dish_list', models.ManyToManyField(to='P5.Dish')),
            ],
        ),
    ]
