# Generated by Django 3.0.7 on 2021-05-17 14:56

from django.db import migrations, models
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('P5', '0002_auto_20210507_1321'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='comment',
        ),
        migrations.AddField(
            model_name='orderdetail',
            name='comment',
            field=models.CharField(blank=True, default=None, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='bill',
            name='change',
            field=djmoney.models.fields.MoneyField(currency_choices=(('EUR', 'EURO €'),), decimal_places=2, default_currency='EUR', max_digits=9, verbose_name='Rückgeld'),
        ),
    ]
