# Generated by Django 3.2.1 on 2021-05-04 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('P5', '0003_auto_20210504_1319'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='confirmation',
            field=models.BooleanField(default=False),
        ),
    ]
